### ISSUE TITLE
厉害

### ISSUE THREAD

**Issue by zhaoxuesong0526** [langyuxiansheng/slider-verification-code#1]

**Comment by zhaoxuesong0526** [comment]
大佬，你是如何发的npm包啊

**Comment by langyuxiansheng** [comment]
这个月项目有点忙,没注意看,给你推荐一篇文章,看看是如何发布的步骤,代码部分的话,要是想测试的话,直接下载我这套框架,改成你自己的就好
URL: https://www.cnblogs.com/wisewrong/archive/2018/12/28/10186611.html

**Comment by langyuxiansheng** [comment]
这个插件可能还有bug........

**Comment by langyuxiansheng** [comment]
bug已修复,有优化建议也可以提出来
