### ISSUE TITLE
关于屏幕大小改变后进度条问题

### ISSUE THREAD

**Issue by bzing** [langyuxiansheng/slider-verification-code#6]
正常情况下进度条可以拉满，但是当我改变页面大小后 ，进度条出现不够或者超出的问题，class=”backgroud“  是固定的px  是否能改变成百分比 满足屏幕改变进度条自适应问题？  我是后端，对前端不是太熟悉，希望知道怎么修改。

**Comment by langyuxiansheng** [comment]
好的 这个问题已经处理了哈

**Comment by langyuxiansheng** [comment]
感谢你的反馈
